In [1]:
import  pandas as pd
import os
os.chdir('/users/sgdbareh/volatile/ECHR_Importance/VectorDB/')
from run_experiments import select_embedding

In [2]:
train = pd.read_pickle('/users/sgdbareh/volatile/ECHR_Importance/VectorDB/train.pkl')

In [2]:
outcome_case = pd.read_pickle('/users/sgdbareh/volatile/ECHR_Importance/Art_3_Data_Process/outcome_cases.pkl')

In [4]:
train = train[['Filename','Subject Matter','appno','extracted_apps']]

In [5]:
new_rows = []
for index, row in train.iterrows():
    for appno in row['extracted_apps']:
        new_row = {
            'Filename': row['Filename'],
            'Subject Matter': row['Subject Matter'],
            'Actual App No': row['appno'],
            'appno': appno
        }
        new_rows.append(new_row)

new_df = pd.DataFrame(new_rows)
#train = pd.concat([train, new_df], ignore_index=True)

In [6]:
new_df.rename(columns={'Subject Matter':'Comm_Case'}, inplace=True)

In [3]:
outcome_case['appno'] = outcome_case['appno'].str.split(';').str[0]

In [4]:
outcome_case.drop_duplicates(subset=['appno'], inplace=True,keep='last')

In [5]:
outcome_case = outcome_case[['File','appno']]

In [6]:
outcome_case.rename(columns={'File':'Filename'}, inplace=True)

In [7]:
outcome_case

        Filename     appno
0      001-67704  31859/96
1       001-4840  40787/98
3       001-4497  44667/98
4       001-4507  42367/98
5       001-4902  44911/98
...          ...       ...
7666  001-214330  57467/15
7667  001-217061  28492/15
7668  001-220484  22854/20
7669  001-224629  38263/08
7670  001-235139  20958/14

[7198 rows x 2 columns]

In [11]:
summarise_data = pd.read_pickle('/users/sgdbareh/volatile/ECHR_Importance/Summarize_Cases/Results/outcome_summaries.pkl')

In [12]:
complete_outcome_data = pd.merge(outcome_case, summarise_data, on='Filename', how='inner')

In [13]:
training_data = pd.merge(new_df, complete_outcome_data, on='appno', how='left')

In [14]:
training_data.columns

Index(['Filename_x', 'Comm_Case', 'Actual App No', 'appno', 'Filename_y',
       '200 Word Summary', '500 Word Summary'],
      dtype='object')

In [15]:
training_data = training_data[['Filename_x','Comm_Case','appno','200 Word Summary']]

In [16]:
training_data.rename(columns={'Filename_x':'Filename','200 Word Summary':'Positive'}, inplace=True)

In [18]:
#FIND NEGATIVE CASES
results = pd.read_pickle('/users/sgdbareh/volatile/ECHR_Importance/VectorDB/cosine_openai_raw_chunk_2048_results.pkl')

In [19]:
for i,j in results.items():

    result_list = []

    for k in j:
        if k == '':
            continue    
        result_list.append(k.split(';')[0])  

    results[i] = result_list[15:]

In [20]:
negative_candidates = pd.DataFrame.from_dict(results, orient='index')

In [21]:
neg_numbers = {}

for index, row in training_data.iterrows():
    # Access the values of each column in the row
    column1_value = row['Filename']
    neg_list = negative_candidates.loc[column1_value].values
    if column1_value not in neg_numbers.keys():
        neg_numbers[column1_value] = 49
    
    #print(neg_list)
    
    neg_candidate = neg_numbers[column1_value]

    while neg_candidate is None:
        neg_numbers[column1_value] -= 1
        neg_candidate = neg_list[neg_numbers[column1_value]]

    neg_numbers[column1_value] -= 1

    #print(neg_candidate)

    training_data.at[index, 'Negative'] = neg_list[neg_candidate]

In [22]:
complete_outcome_data.rename(columns={'appno':'Negative'}, inplace=True)

In [23]:
training_data_pos_neg = pd.merge(training_data, complete_outcome_data, on='Negative', how='inner')

In [24]:
training_data_pos_neg = training_data_pos_neg[['Filename_x','Comm_Case','Positive','200 Word Summary']]

In [25]:
training_data_pos_neg.rename(columns={'Filename_x':'Filename','200 Word Summary':'Negative'}, inplace=True)

In [26]:
#replace comm case facts with summaries

comm_summaries = pd.read_pickle('/users/sgdbareh/volatile/ECHR_Importance/Summarize_Cases/Results/comm_train_summaries.pkl')

In [27]:
training_data_pos_neg = pd.merge(training_data_pos_neg, comm_summaries, on='Filename', how='inner')

In [28]:
training_data_pos_neg.drop(columns=['Comm_Case','500 Word Summary'], inplace=True)

In [29]:
training_data_pos_neg.rename(columns={'200 Word Summary':'Comm_Case'}, inplace=True)

In [30]:
training_data_pos_neg.to_pickle('/users/sgdbareh/volatile/ECHR_Importance/BERT-rerank/BERT_training_data_df.pkl')

In [31]:
training_data_pos_neg

,Filename,Positive,Negative,Comm_Case
0,001-194607,The case involves a father and son from Surgut...,"Ms. Tamara Pavlovna Rokhlina, a Russian nation...","The case involves four Russian women, Natalya ..."
1,001-194607,The case involves multiple applicants who were...,"The applicant, born in 1956, was detained by p...","The case involves four Russian women, Natalya ..."
2,001-194607,"The applicant, born in 1976 and residing in Pa...","The applicants, Russian nationals from the Che...","The case involves four Russian women, Natalya ..."
3,001-194607,"The case involves three siblings, X, Y, and Z,...","Mr. Ali Nurdinovich Ibragimov, a Russian natio...","The case involves four Russian women, Natalya ..."
4,001-194607,"The applicant, a police officer, was arrested ...","The applicant, born in 1953 and residing in Ka...","The case involves four Russian women, Natalya ..."
...,...,...,...,...
2320,001-145069,"The case involves Ms. L.C.B., a British nation...","Mr. Mihails Panasenkovs, a non-citizen of Latv...","Mr. Boris Mozer, a Moldovan national, was deta..."
2321,001-145069,"The applicant, a Greek-Cypriot teacher born in...","The applicant, born in 1980 and residing in Bă...","Mr. Boris Mozer, a Moldovan national, was deta..."
2322,001-145069,"The applicants, two brothers from Saint-Josse-...","On 17 July 2005, M.P., an inmate at Požarevac ...","Mr. Boris Mozer, a Moldovan national, was deta..."
2323,001-176188,"The applicant, born in 1967, was arrested on 1...","The applicant, born in 1979 and residing in Mo...",The case concerns an applicant who was remande...
2324,001-176188,"The applicant, born in 1957, was the secretary...","Józef Bogulak, a Polish national, was apprehen...",The case concerns an applicant who was remande...

#### test

In [32]:
from sentence_transformers import InputExample

In [32]:
# Initialize an empty list for train_samples
train_samples = []

# Iterate over the DataFrame rows
for index, row in df.iterrows():
    # Create InputExample for positive label
    train_samples.append(InputExample(texts=[row['comm_case'], row['positive']], label=label2int["pos"]))
    # Create InputExample for negative label
    train_samples.append(InputExample(texts=[row['comm_case'], row['negative']], label=label2int["neg"]))

NameError: name 'df' is not defined

In [ ]:
# REPLACE COMM CASE WITH SUMMARY TOO!!!!

In [ ]:
#for loop

# for each case in train_subset
# find the text of a extracted appno and pair it as positive
# then find not very similar case and pair as negative do this for all extracted app nos

### use openai 1024 to find the least similar


## split this 80/20 cros validation to train 5 different models for train/validation


#eval on test set 

#label2int = {"neg": 0, "pos": 1}
#train_samples = [
#    InputExample(texts=["sentence1", "sentence2"], label=label2int["neg"]),
#    InputExample(texts=["Another", "pair"], label=label2int["pos"]),
#]